a = True
if not True:
    print("true")
else:
    print("False")
price = 10
age = 18
entry = True
if price<10:
    print("it less than 10")
if age<18:
    print("do not Enter")
else:
    print("Not allowed to enter")
Age = input("What is your age?:")
if int(Age) >=18:
    print("enter")
if Age >= 50:
    print("senior citizen") 
elif int(Age) >=13 and int(Age) < 18:
    print("Adult")
else:
    print("Do not Enter")
